baseURL = "https://redopop.com/"
disableKinds = [
  "taxonomy",
  "taxonomyTerm",
]
enableRobotsTXT = true
footnoteReturnLinkContents = "↩"
languageCode = "en-US"
rssLimit = 20
pygmentsUseClasses = true

[author]
  name = "Joe Bartlett"
  email = "joe@redopop.com"
  uri = "https://redopop.com/"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["atom"]

[outputFormats]
  [outputFormats.Atom]
    baseName = "feed"
    isPlainText = false
    mediaType = "application/atom+xml"

[outputs]
  home = ["HTML", "Atom"]
  page = ["HTML"]
  section = ["HTML"]
